# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI-MacOS

on:
  push:
    branches: [ "practice3" ]
  pull_request:
    branches: [ "practice3" ]

jobs:
  build-and-test:

    runs-on: macos-latest
    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v4


    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    
    - name: Build and Test
      run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI-MacOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES

